# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 197eebf616ca162ae942a4b6cd31a6f99c54405ed05f3cf9ef9e0c3ac753c7a79ce1499cfcd450dad26e94d77e3c86581e4ca2bac2692334bc7f7552112c0231

test:
  secret_key_base: 7da388796371a01d928d0da9d04b39299dccd6899f0af645a0f46314c45e2e9849df070b3e615ea5a6d859d03fd9f2764a37f985dd1a85211171b18c29557209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
